import type { AsyncSorterTask } from './types';

export const asyncSorterTasks: AsyncSorterTask[] = [
  {
    id: 1,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => console.log('2'), 0);",
      "Promise.resolve().then(() => console.log('3'));",
      "console.log('4');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['3'],
      macrotasks: ['2'],
      outputOrder: ['1', '4', '3', '2'],
    },
  },

  {
    id: 2,
    type: 'async-sorter',
    codeSnippet: [
      'setTimeout(() => {',
      "  console.log('1');",
      "  Promise.resolve().then(() => console.log('2'));",
      "  console.log('3');",
      '}, 0);',
      "console.log('4');",
      "Promise.resolve().then(() => console.log('5'));",
    ],
    blocks: [
      { id: 'b1', code: 'setTimeout callback', label: '1' },
      {
        id: 'b2',
        code: 'Promise.then callback (inside setTimeout)',
        label: '2',
      },
      { id: 'b3', code: 'setTimeout callback', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
      { id: 'b5', code: 'Promise.then callback', label: '5' },
    ],
    answer: {
      callStack: ['4'],
      microtasks: ['5', '2'],
      macrotasks: ['1', '3'],
      outputOrder: ['4', '5', '1', '3', '2'],
    },
  },
  {
    id: 3,
    type: 'async-sorter',
    codeSnippet: [
      "(async () => {console.log('1');",
      'await Promise.resolve();',
      "console.log('2');",
      '})();',
      "console.log('3');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'async/await continuation', label: '2' },
      { id: 'b3', code: "console.log('3')", label: '3' },
    ],
    answer: {
      callStack: ['1', '3'],
      microtasks: ['2'],
      macrotasks: [],
      outputOrder: ['1', '3', '2'],
    },
  },
  {
    id: 4,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => console.log('2')).then(() => console.log('3'));",
      "setTimeout(() => console.log('4'), 0);",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback (chain)', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
    ],
    answer: {
      callStack: ['1'],
      microtasks: ['2', '3'],
      macrotasks: ['4'],
      outputOrder: ['1', '2', '3', '4'],
    },
  },
  {
    id: 5,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "queueMicrotask(() => console.log('2'));",
      "console.log('3');",
      "setTimeout(() => console.log('4'), 0);",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'queueMicrotask callback', label: '2' },
      { id: 'b3', code: "console.log('3')", label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
    ],
    answer: {
      callStack: ['1', '3'],
      microtasks: ['2'],
      macrotasks: ['4'],
      outputOrder: ['1', '3', '2', '4'],
    },
  },

  {
    id: 6,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => {console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      '});',
      "console.log('4');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['2'],
      macrotasks: ['3'],
      outputOrder: ['1', '4', '2', '3'],
    },
  },
  {
    id: 7,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => {console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      '}, 0);',
      "console.log('4');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback (nested)', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: [],
      macrotasks: ['2', '3'],
      outputOrder: ['1', '4', '2', '3'],
    },
  },
  {
    id: 8,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => console.log('2'), 0);",
      "Promise.resolve().then(() => { console.log('3');",
      "  Promise.resolve().then(() => console.log('4'));",
      '});',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'Promise.then callback (nested)', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['3', '4'],
      macrotasks: ['2'],
      outputOrder: ['1', '5', '3', '4', '2'],
    },
  },
  {
    id: 9,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => {console.log('2');",
      "  Promise.resolve().then(() => console.log('3'));",
      "  setTimeout(() => console.log('4'), 0);",
      '});',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback (nested)', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['2', '3'],
      macrotasks: ['4'],
      outputOrder: ['1', '5', '2', '3', '4'],
    },
  },
  {
    id: 10,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "(async () => { console.log('2');",
      '  await Promise.resolve();',
      "  console.log('3');",
      '})();',
      "setTimeout(() => console.log('4'), 0);",
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: "console.log('2')", label: '2' },
      { id: 'b3', code: 'async/await continuation', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '2', '5'],
      microtasks: ['3'],
      macrotasks: ['4'],
      outputOrder: ['1', '2', '5', '3', '4'],
    },
  },
  {
    id: 11,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      'const p = Promise.resolve();',
      "p.then(() => console.log('2'));",
      "p.then(() => console.log('3'));",
      "setTimeout(() => console.log('4'), 0);",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
    ],
    answer: {
      callStack: ['1'],
      microtasks: ['2', '3'],
      macrotasks: ['4'],
      outputOrder: ['1', '2', '3', '4'],
    },
  },
  {
    id: 12,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => { console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      "  setTimeout(() => console.log('4'), 0);",
      '});',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['2'],
      macrotasks: ['3', '4'],
      outputOrder: ['1', '5', '2', '3', '4'],
    },
  },
  {
    id: 13,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      'setTimeout(() => {',
      "  console.log('2');",
      "  Promise.resolve().then(() => console.log('3'));",
      '}, 0);',
      "console.log('4');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      {
        id: 'b3',
        code: 'Promise.then callback (inside setTimeout)',
        label: '3',
      },
      { id: 'b4', code: "console.log('4')", label: '4' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['3'],
      macrotasks: ['2'],
      outputOrder: ['1', '4', '2', '3'],
    },
  },
  {
    id: 14,
    type: 'async-sorter',
    codeSnippet: [
      'setTimeout(async () => {',
      "  console.log('1');",
      '  await Promise.resolve();',
      "  console.log('2');",
      '}, 0);',
      "console.log('3');",
    ],
    blocks: [
      { id: 'b1', code: 'setTimeout callback', label: '1' },
      {
        id: 'b2',
        code: 'async/await continuation (inside setTimeout)',
        label: '2',
      },
      { id: 'b3', code: "console.log('3')", label: '3' },
    ],
    answer: {
      callStack: ['3'],
      microtasks: ['2'],
      macrotasks: ['1'],
      outputOrder: ['3', '1', '2'],
    },
  },
  {
    id: 15,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => {console.log('2');",
      "  Promise.resolve().then(() => {console.log('3');",
      "    Promise.resolve().then(() => console.log('4'));",
      '  });',
      '}, 0);',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'Promise.then callback (nested)', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['3', '4'],
      macrotasks: ['2'],
      outputOrder: ['1', '5', '2', '3', '4'],
    },
  },
  {
    id: 16,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => console.log('2'), 0);",
      "Promise.resolve().then(() => console.log('3'));",
      "setTimeout(() => console.log('4'), 0);",
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['3'],
      macrotasks: ['2', '4'],
      outputOrder: ['1', '5', '3', '2', '4'],
    },
  },
  {
    id: 17,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      'Promise.resolve().then(() => {',
      "  console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      '});',
      "Promise.resolve().then(() => console.log('4'));",
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback', label: '3' },
      { id: 'b4', code: 'Promise.then callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['2', '4'],
      macrotasks: ['3'],
      outputOrder: ['1', '5', '2', '4', '3'],
    },
  },
  {
    id: 18,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => console.log('2'));",
      "queueMicrotask(() => console.log('3'));",
      "setTimeout(() => console.log('4'), 0);",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'queueMicrotask callback', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
    ],
    answer: {
      callStack: ['1'],
      microtasks: ['2', '3'],
      macrotasks: ['4'],
      outputOrder: ['1', '2', '3', '4'],
    },
  },
  {
    id: 19,
    type: 'async-sorter',
    codeSnippet: [
      "const f = () => console.log('1');",
      "console.log('2');",
      "Promise.resolve().then(() => console.log('3'));",
      "setTimeout(() => console.log('4'), 0);",
      "console.log('5');",
      'f();',
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: "console.log('2')", label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'setTimeout callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['2', '5', '1'],
      microtasks: ['3'],
      macrotasks: ['4'],
      outputOrder: ['2', '5', '1', '3', '4'],
    },
  },
  {
    id: 20,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => {console.log('2');",
      "  queueMicrotask(() => console.log('3'));",
      '});',
      "console.log('4');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      {
        id: 'b3',
        code: 'queueMicrotask callback (scheduled inside Promise.then)',
        label: '3',
      },
      { id: 'b4', code: "console.log('4')", label: '4' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['2', '3'],
      macrotasks: [],
      outputOrder: ['1', '4', '2', '3'],
    },
  },
  {
    id: 21,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => {console.log('2');",
      "  Promise.resolve().then(() => console.log('3'));",
      "  queueMicrotask(() => console.log('4'));",
      '}, 0);',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: 'queueMicrotask callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['3', '4'],
      macrotasks: ['2'],
      outputOrder: ['1', '5', '2', '3', '4'],
    },
  },
  {
    id: 22,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "(async () => {console.log('2');",
      '  await Promise.resolve();',
      "  console.log('3');",
      '})();',
      "Promise.resolve().then(() => console.log('4'));",
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: "console.log('2')", label: '2' },
      { id: 'b3', code: 'async/await continuation', label: '3' },
      { id: 'b4', code: 'Promise.then callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '2', '5'],
      microtasks: ['3', '4'],
      macrotasks: [],
      outputOrder: ['1', '2', '5', '3', '4'],
    },
  },
  {
    id: 23,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => {console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      "  Promise.resolve().then(() => console.log('4'));",
      '});',
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback', label: '3' },
      {
        id: 'b4',
        code: 'Promise.then callback (scheduled inside Promise.then)',
        label: '4',
      },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['2', '4'],
      macrotasks: ['3'],
      outputOrder: ['1', '5', '2', '4', '3'],
    },
  },
  {
    id: 24,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => console.log('2'), 0);",
      "Promise.resolve().then(() => console.log('3'));",
      "console.log('4');",
      "Promise.resolve().then(() => console.log('5'));",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'Promise.then callback', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
      { id: 'b5', code: 'Promise.then callback', label: '5' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['3', '5'],
      macrotasks: ['2'],
      outputOrder: ['1', '4', '3', '5', '2'],
    },
  },
  {
    id: 25,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => {console.log('2');",
      "  setTimeout(() => console.log('3'), 0);",
      '}, 0);',
      "Promise.resolve().then(() => console.log('4'));",
      "console.log('5');",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'setTimeout callback (nested)', label: '3' },
      { id: 'b4', code: 'Promise.then callback', label: '4' },
      { id: 'b5', code: "console.log('5')", label: '5' },
    ],
    answer: {
      callStack: ['1', '5'],
      microtasks: ['4'],
      macrotasks: ['2', '3'],
      outputOrder: ['1', '5', '4', '2', '3'],
    },
  },
  {
    id: 26,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "Promise.resolve().then(() => {console.log('2');",
      '  (async () => {',
      "    console.log('3');",
      '    await Promise.resolve();',
      "    console.log('4');",
      '  })();',
      '});',
      "setTimeout(() => console.log('5'), 0);",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'Promise.then callback', label: '2' },
      {
        id: 'b3',
        code: 'async IIFE inside Promise.then (sync part)',
        label: '3',
      },
      { id: 'b4', code: 'async/await continuation (after await)', label: '4' },
      { id: 'b5', code: 'setTimeout callback', label: '5' },
    ],
    answer: {
      callStack: ['1'],
      microtasks: ['2', '3', '4'],
      macrotasks: ['5'],
      outputOrder: ['1', '2', '3', '4', '5'],
    },
  },
  {
    id: 27,
    type: 'async-sorter',
    codeSnippet: [
      "console.log('1');",
      "setTimeout(() => console.log('2'), 0);",
      "queueMicrotask(() => console.log('3'));",
      "console.log('4');",
      "Promise.resolve().then(() => console.log('5'));",
    ],
    blocks: [
      { id: 'b1', code: "console.log('1')", label: '1' },
      { id: 'b2', code: 'setTimeout callback', label: '2' },
      { id: 'b3', code: 'queueMicrotask callback', label: '3' },
      { id: 'b4', code: "console.log('4')", label: '4' },
      { id: 'b5', code: 'Promise.then callback', label: '5' },
    ],
    answer: {
      callStack: ['1', '4'],
      microtasks: ['3', '5'],
      macrotasks: ['2'],
      outputOrder: ['1', '4', '3', '5', '2'],
    },
  },
];
